// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hLqGVvmVnnUEmCqoOQAhunTQoMDIrrE',
    appId: '1:972733993724:web:2a27131f13b194055dfd79',
    messagingSenderId: '972733993724',
    projectId: 'todoapp-b0aee',
    authDomain: 'todoapp-b0aee.firebaseapp.com',
    storageBucket: 'todoapp-b0aee.appspot.com',
    measurementId: 'G-XRXLN0SFWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYGe9d9ZHIZ5vE3OjAHWYCfSKJhreT98',
    appId: '1:972733993724:android:38be004307d21fca5dfd79',
    messagingSenderId: '972733993724',
    projectId: 'todoapp-b0aee',
    storageBucket: 'todoapp-b0aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrY1wiVou6xaZTD6lXhahK9snWbkftxc',
    appId: '1:972733993724:ios:73d3f6049bb850655dfd79',
    messagingSenderId: '972733993724',
    projectId: 'todoapp-b0aee',
    storageBucket: 'todoapp-b0aee.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrY1wiVou6xaZTD6lXhahK9snWbkftxc',
    appId: '1:972733993724:ios:73d3f6049bb850655dfd79',
    messagingSenderId: '972733993724',
    projectId: 'todoapp-b0aee',
    storageBucket: 'todoapp-b0aee.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9hLqGVvmVnnUEmCqoOQAhunTQoMDIrrE',
    appId: '1:972733993724:web:03e5fa50e151352e5dfd79',
    messagingSenderId: '972733993724',
    projectId: 'todoapp-b0aee',
    authDomain: 'todoapp-b0aee.firebaseapp.com',
    storageBucket: 'todoapp-b0aee.appspot.com',
    measurementId: 'G-JMZ9V6R1V0',
  );
}
